export const ANALYSIS_QUIPS = [
  "Counting your contractions...",
  "Looking for em dashes...",
  "Checking if ChatGPT wrote this...",
  "Scanning for suspiciously perfect grammar...",
  "Hunting for triple lists...",
  "Measuring sentence uniformity...",
  "Searching for 'it is important to note'...",
  "Checking vocabulary diversity...",
  "Looking for 'furthermore' and 'moreover'...",
  "Analysing burstiness patterns...",
  "Comparing against known AI fingerprints...",
  "Checking if you used any slang...",
  "Counting hedging phrases...",
  "Looking for overly polished prose...",
  "Checking negation density...",
  "Searching for 'delve' and 'utilize'...",
  "Measuring paragraph regularity...",
  "Hunting for topic-sentence patterns...",
  "Checking if every paragraph is the same length...",
  "Looking for suspiciously balanced arguments...",
  "Scanning for generic conclusions...",
  "Checking contraction avoidance...",
  "Measuring phrase repetition rates...",
  "Looking for that ChatGPT politeness...",
  "Checking if sentences start with 'Additionally'...",
  "Scanning for robotic transitions...",
  "Hunting for lists of exactly three things...",
  "Checking word choice diversity...",
  "Looking for unnaturally smooth flow...",
  "Counting instances of 'However,'...",
  "Measuring complexity variance...",
  "Checking for the Claude em dash signature...",
  "Looking for missing personality...",
  "Scanning for formulaic structure...",
  "Checking if opinions are suspiciously balanced...",
  "Hunting for 'In conclusion' patterns...",
  "Looking for AI-typical formatting...",
  "Counting filler transitions...",
  "Checking sentence length variance...",
  "Looking for absent contractions...",
  "Scanning for 'it's worth noting'...",
  "Measuring writing burstiness...",
  "Checking for human imperfections...",
  "Looking for copy-paste tells...",
  "Analysing structural patterns...",
  "Checking if anyone actually talks like this...",
  "Scanning for that GPT-4 cadence...",
  "Hunting for missing typos...",
  "Checking vocabulary against LLM frequency...",
  "Almost there, just double-checking...",
];
