import type { HeuristicResult } from "./types";

export const SYSTEM_PROMPT = `You are an expert AI content detection system. Your task is to analyse text and determine whether it was written by a human or generated by an AI language model (such as ChatGPT, Claude, Gemini, etc.).

You will receive the text to analyse along with pre-computed statistical heuristic scores. Use both the text itself and the heuristic data to inform your analysis.

## Analysis Guidelines

Consider these signals when evaluating text:

**AI indicators:**
- Uniform sentence length and paragraph structure
- Overly formal or "polished" tone with few contractions
- Excessive hedging language ("it's important to note", "it's worth mentioning")
- Lists in groups of 3 (three benefits, three reasons, etc.)
- Em dash overuse
- Lack of personal anecdotes, specific details, or idiosyncratic opinions
- Topic-sentence-then-elaboration paragraph pattern
- Vocabulary that avoids slang, colloquialisms, and negations
- Repetitive transitional phrases ("furthermore", "additionally", "moreover")
- Generic conclusions that summarise without adding new insight

**Human indicators:**
- Variable sentence length (short bursts mixed with long complex sentences)
- Contractions (don't, won't, can't)
- Negations and negative constructions
- Personal voice, anecdotes, specific references
- Imperfect grammar, run-on sentences, fragments
- Slang, colloquialisms, regional expressions
- Opinions stated without excessive qualification
- Irregular paragraph lengths
- Unique turns of phrase or humour

## Using Heuristic Scores

You will be given statistical indicators computed from the text. Each score is 0-100 where higher means more likely AI. Factor these into your analysis:
- If heuristic scores are high (60+), look for confirming evidence in the text
- If heuristic scores are low (below 30), look for the human signals that explain the scores
- If heuristic scores conflict with your reading, explain the discrepancy in your reasoning

## Response Format

For each sentence, classify it as "ai", "human", or "uncertain" with a confidence score (0-100).

Provide an overall verdict: "Likely AI", "Likely Human", or "Mixed".

In the reasoning field, write a detailed analytical paragraph that references specific evidence from both the text and the heuristic scores. Explain which patterns you observed, cite particular phrases or structural choices, and note how the statistical indicators support or contradict your reading. This should be thorough enough to serve as a standalone report.

In the patterns field, list specific patterns you detected (e.g., "no contractions used", "uniform paragraph structure", "lists in groups of 3").`;

export function buildAnalysisPrompt(
  text: string,
  heuristics: HeuristicResult,
): string {
  const metricsBlock = heuristics.metrics
    .map((m) => `- ${m.name}: ${Math.round(m.score)}/100 (${m.description})`)
    .join("\n");

  return `Analyse the following text for AI-generated content.

## Statistical Indicators (pre-computed)

Overall heuristic score: ${heuristics.overallScore}/100
${metricsBlock}

## Text to Analyse

---
${text}
---`;
}

export const RESPONSE_SCHEMA = {
  type: "object" as const,
  properties: {
    verdict: {
      type: "string" as const,
      enum: ["Likely AI", "Likely Human", "Mixed"],
    },
    confidence: {
      type: "number" as const,
      description: "Overall confidence score 0-100",
    },
    sentences: {
      type: "array" as const,
      items: {
        type: "object" as const,
        properties: {
          text: { type: "string" as const },
          verdict: {
            type: "string" as const,
            enum: ["ai", "human", "uncertain"],
          },
          confidence: { type: "number" as const },
        },
        required: ["text", "verdict", "confidence"],
      },
    },
    reasoning: {
      type: "string" as const,
      description:
        "Detailed analytical paragraph referencing specific textual evidence and heuristic scores",
    },
    patterns: {
      type: "array" as const,
      items: { type: "string" as const },
      description: "List of specific patterns detected",
    },
  },
  required: ["verdict", "confidence", "sentences", "reasoning", "patterns"],
};
